language: python
python:
- '2.7'
env:
  global:
  - DJANGO_SETTINGS_MODULE='bucketlist.settings.test'
install:
- pip install -r requirements/testing.txt
- pip install coveralls
script:
- python bucketlist/manage.py collectstatic --noinput --settings=bucketlist.settings.test
- python bucketlist/manage.py makemigrations --settings=bucketlist.settings.test
- python bucketlist/manage.py migrate --settings=bucketlist.settings.test
- python bucketlist/manage.py test --noinput â€“with-coverage
after_success:
- coveralls
deploy:
  provider: heroku
  buildpack: python
  api_key:
    secure: KmYdDlsoUz7tci0V3TprxBNLz92Cl2C3AENDkhDOLwv5J/8OWjHS/OKCkPC2Hu9YFhqUeC2MG8n4EvW9plGFU3d+Rdw2KWgchVMxdnAf6y2Q52XZiAB4waFB4fNFmHI/K5FUhOpeRuS69YZ6ozV6Mo8XUPllLE6MexFDoQ3bGuZjT7TUqyk74+9tnpp7Fb9nVttXtFsyEUOGPLsX/XyKhAwOukOqyy1dIE5lOFp7Ds2fnBHKCX21e2jfHCqTpBsIZY+uVy+eicFKQLNakMRb3dwytuiLYq7Eyta/99DrOATAGhYrkYdAt4eem1ngt4R4goVtc4viSNbRxNlVlQb5ykU75hxL3/W5XtRkTiUlOuz1tfufA44mxv62BzwQngd5mOULq9b/eSBR7E5nWQIEIy3u2JLG59ecQ6mWpmKyN0bGjdgemBdMaZBlss/eF7/7pFdJ5AcMfYPgltfu67CMdtuM1NFhEb/vncBgejV5r2tCCpg6hwTEBVg+a4kCK+M4S23cMmQzDXGHosdxLaFsUgp0xIbVgod3XGct9LkJ2YUbhRW+yVwNZNukULjDdOAjG5F719RyIPkGBWvruQBnyOkav1cklJdAsz71Joet/W3ziqCCcQPldmA3u7CCavCKUs0tnGYQhbFLf/V6Azwd157B4v5fVfy5FLK9W7adSds=
  app:
    develop: bucketlist-staging
  run:
    - "export DJANGO_SETTINGS_MODULE=troupon.settings.production"
    - "python bucketlist/manage.py collectstatic --noinput"
    - "python bucketlist/manage.py makemigrations"
    - "python bucketlist/manage.py migrate"
    - "gunicorn bucketlist.wsgi --pythonpath=bucketlist --log-file -"
